Repository Vincent440/hotel-worx, pull requests merged in 2019-07, with the labels that each got.

#39 Passport
  controllers/passportController.js
  controllers/userController.js
  models/userPassport.js
  package.json
  routes/api/index.js
  routes/api/login.js
  routes/api/logout.js
  routes/index.js
  routes/login.js
  server.js
Labels: Completion Requirement

#57 Login react
  client/src/App.js
  client/src/components/Header/index.js
  client/src/components/PrivateRoute.js
  client/src/components/infoPart/index.js
  client/src/components/loginForm/loginForm.js
  client/src/pages/Logout.js
  client/src/pages/authTest.js
  client/src/pages/dashboard/dashboard.js
  client/src/pages/login.js
  client/src/utils/LoginAPI.js
  controllers/passportController.js
  controllers/userController.js
  models/userPassport.js
  routes/api/index.js
  routes/api/login.js
  routes/api/logout.js
  routes/api/users.js
  routes/index.js
  server.js
Labels: Completion Requirement, Minimum Viable Product

#58 changed login file name and imported name
  client/src/App.js
  client/src/pages/login.js
Labels: Completion Requirement, bug

#65 Change login
  client/src/App.js
  client/src/pages/Logout.js
  client/src/utils/authapi.js
  controllers/passportController.js
  controllers/userController.js
  routes/api/customers.js
  routes/api/login.js
  routes/api/logout.js
  routes/api/reservations.js
  routes/api/room-types.js
  routes/api/rooms.js
Labels: Completion Requirement, bug

#67 set up logout button and removed margin from top of the button on inf…
  client/src/App.js
  client/src/components/infoPart/index.js
  client/src/pages/allreservations/allreservations.js
  client/src/pages/arrivals/arrivals.js
  client/src/pages/billing/billing.js
  client/src/pages/checkouts/checkouts.js
  client/src/pages/dashboard/dashboard.js
  client/src/pages/detailedAvailability/detailedAvailability.js
  client/src/pages/houseStatus/houseStatus.js
  client/src/pages/housekeeping/housekeeping.js
  client/src/pages/inhouse/inhouse.js
  client/src/pages/newreservation/newreservation.js
  client/src/pages/payment/payment.js
  client/src/pages/reservation/reservation.js
  client/src/pages/updatereservation/updatereservation.js
  routes/api/logout.js
Labels: Completion Requirement

#68 fixing test reservation info pane props
  client/src/pages/newreservation/reservationTest.js
Labels: Completion Requirement, bug

#77 Mysql sessions
  config/connection.js
  config/promiseConnection.js
  docs/README.md
  package.json
  server.js
Labels: Breaking Change, Completion Requirement, Minimum Viable Product, enhancement

#81 Npm removal
  client/package.json
  client/src/components/infoPart/index.js
  package.json
Labels: Breaking Change, Completion Requirement

#86 Readme environment update
  docs/README.md
Labels: Documentation

#90 App conditional render v2
  client/src/App.js
  client/src/UserContext.js
  client/src/components/PrivateRoute.js
  client/src/components/RenderIfAId.js
  client/src/components/infoPart/index.js
  client/src/pages/allreservations/allreservations.js
  client/src/pages/arrivals/arrivals.js
  client/src/pages/billing/billing.js
  client/src/pages/checkouts/checkouts.js
  client/src/pages/dashboard/dashboard.js
  client/src/pages/detailedAvailability/detailedAvailability.js
  client/src/pages/houseStatus/houseStatus.js
  client/src/pages/housekeeping/housekeeping.js
  client/src/pages/inhouse/inhouse.js
  client/src/pages/login/login.js
  client/src/pages/maintenance/maintenance.js
  client/src/pages/newreservation/newreservation.js
  client/src/pages/newreservation/reservationTest.js
  client/src/pages/payment/payment.js
  client/src/pages/reservation/reservation.js
  client/src/pages/updatereservation/updatereservation.js
  client/src/utils/authapi.js
  config/passportConfig.js
  routes/api/login.js
  routes/api/logout.js
  server.js
Labels: Completion Requirement

#93 Infopart move
  client/src/App.js
  client/src/components/infoPart/index.js
  client/src/components/infoPart/style.css
  client/src/index.css
  client/src/pages/allreservations/allreservations.js
  client/src/pages/arrivals/arrivals.js
  client/src/pages/billing/billing.js
  client/src/pages/checkouts/checkouts.js
  client/src/pages/dashboard/dashboard.js
  client/src/pages/dashboardMaster/dashMaster.js
  client/src/pages/detailedAvailability/detailedAvailability.js
  client/src/pages/houseStatus/houseStatus.js
  client/src/pages/housekeeping/housekeeping.js
  client/src/pages/inhouse/inhouse.js
  client/src/pages/login/login.js
  client/src/pages/maintenance/maintenance.js
  client/src/pages/newreservation/newreservation.js
  client/src/pages/newreservation/reservationTest.js
  client/src/pages/payment/payment.js
  client/src/pages/reservation/reservation.js
  client/src/pages/updatereservation/updatereservation.js
Labels: Completion Requirement, enhancement

#94 removed scrollbar by removing padding and margin from container
  client/src/App.js
  client/src/components/infoPart/index.js
  client/src/components/infoPart/style.css
  client/src/pages/newreservation/style.css
Labels: bug, enhancement

#118 Mike32
  client/src/pages/arrivals/arrivals.js
  client/src/pages/billing/billing.js
  client/src/pages/payment/payment.js
  client/src/pages/payment/style3.css
  client/src/utils/api.js
  config/schema.sql
  config/seeds.sql
  models/invoice.js
  models/res_room.js
  routes/api/hw.js
Labels: Bonus Functionality/Icebox
